create table if not exists public.sim_report_slides (
  id bigint generated by default as identity primary key,
  report_id text not null,
  slide_no integer not null check (slide_no between 1 and 3),
  payload jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now(),
  unique (report_id, slide_no)
);

alter table public.sim_report_slides enable row level security;

-- Для внутреннего прототипа. Перед публикацией лучше заменить на авторизацию.
create policy "allow anonymous read"
on public.sim_report_slides for select
to anon
using (true);

create policy "allow anonymous insert"
on public.sim_report_slides for insert
to anon
with check (true);

create policy "allow anonymous update"
on public.sim_report_slides for update
to anon
using (true)
with check (true);
